InspiraLibertad/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using InspiraLibertad.Models;
using InspiraLibertad.Clases;

namespace InspiraLibertad.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILDBContext _context;

        public IndexModel(ILDBContext context)
        {
            _context = context;
        }

        Stack<int> Cursos = new Stack<int>();
        Stack<string> noCursos = new Stack<string>();
        public Compras compra = new Compras();


        [BindProperty]
        public InputCursos inpCursos { get; set; }
        public void OnPostComprar()
        {

            if(inpCursos.InpCursos0 != -1)
            {
                Comprobaciones(inpCursos.InpCursos0);
            }
            if(inpCursos.InpCursos1 != -1)
            {
                Comprobaciones(inpCursos.InpCursos1);
            }
            if (inpCursos.InpCursos2 != -1)
            {
                Comprobaciones(inpCursos.InpCursos2);
            }

            if(Cursos.Count() > 0)
            {
                
                foreach(var curso in Cursos)
                {
                    compra.ClienteId = Convert.ToInt32(SessionHelper.GetNameIndentifier(User));
                    compra.ProductoId = curso;

                    _context.Compras.Add(compra);
                    _context.SaveChanges();

                    ViewData["res2"] = "1";
                }
            }
        }

        public void Comprobaciones(int id)
        {
            bool numVeces = _context.Compras.Where(p => p.ClienteId.ToString() == SessionHelper.GetNameIndentifier(User) && p.ProductoId == id).Any();

            if (numVeces)
            {
                var curso = _context.Producto.Where(p => p.Id == id).SingleOrDefault();
                noCursos.Push(curso.Nombre);
                ViewData["noCursos"] = noCursos;
                ViewData["res1"] = "1";
            }
            else
            {
                Cursos.Push(id);
            }
        }
    }
}

InspiraLibertad/Pages/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using InspiraLibertad.Models;
using System.Security.Cryptography;
using System.Text;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;

namespace InspiraLibertad.Pages
{
    public class LoginModel : PageModel
    {
        public int res = -1;

        private readonly InspiraLibertad.Models.ILDBContext _context;

        public LoginModel(InspiraLibertad.Models.ILDBContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Login Login { get; set; }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            string clave = Login.Password;
            SHA256Managed sha = new SHA256Managed();
            byte[] buffer = Encoding.Default.GetBytes(clave);
            byte[] claveCifrada = sha.ComputeHash(buffer);
            string claveCifradaString = BitConverter.ToString(claveCifrada).Replace("-", "");

            Login.Password = claveCifradaString;

            var usuario = _context.Cliente.Where(p => p.NombreUsuario == Login.NombreUsuario && p.Password == Login.Password).SingleOrDefault();
            if(usuario == null)
            {
                res = 1;
                return Page();
            }
            else if(usuario != null && usuario.Token != null)
            {
                res = 0;
                return Page();
            }
            else
            {
                var usuarioT = _context.Cliente.Where(p => p.NombreUsuario == Login.NombreUsuario && p.Password == Login.Password && p.Token == null).SingleOrDefault();

                var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme, ClaimTypes.Name, ClaimTypes.Role);
                identity.AddClaim(new Claim(ClaimTypes.NameIdentifier, usuario.Id.ToString()));
                identity.AddClaim(new Claim(ClaimTypes.Name, usuario.NombreUsuario.ToString()));

                var principal = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal, new AuthenticationProperties { ExpiresUtc = DateTime.Now.AddDays(1), IsPersistent = true });
                ViewData["res3"] = "1";
                return Redirect("/Index");
           
            }
            
        }

        public async Task<IActionResult> OnGetLogout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToPage("./Index");
        }
    }
}

InspiraLibertad/Pages/Shared/_Layout.cshtml
@using InspiraLibertad.Clases

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        @if (!User.Identity.IsAuthenticated)
        {
            <input type="hidden" id="inpInicio" value="0">
        }
        else
        {
            <input type="hidden" id="inpInicio" value="1">
        }

        <ul class="nav justify-content-end align-items-center mr-4 mt-4 ">
            @if (User.Identity.IsAuthenticated)
            {
                <li class='text-success h-50'>@SessionHelper.GetName(User)</li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-page="/Login" asp-page-handler="Logout">Cerrar sesión</a>
                </li>
            }
            else
            {
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-page="/Login">Iniciar sesión</a>
                </li>
            }

            <li class="nav-item">
                <a class="nav-link text-dark" asp-area="" asp-page="/registro">Registro</a>
            </li>
            <li>
                <button type="button" class="btn btn-success position-relative" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart3" viewBox="0 0 16 16">
                        <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                    </svg>
                    <span id="spanCant" class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                        0
                    </span>
                </button>
            </li>
        </ul>
        <nav class="navbar navbar-expand-xl navbar-toggleable-xl navbar-light bg-white border-bottom box-shadow mb-3 mt-2">
            <div class="container">
                <a class="navbar-brand text-success" asp-area="" asp-page="/Index"><h4>InspiraLibertad</h4></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-xl-inline-flex flex-xl-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/queEs">Que es?</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/depAdicc">Dependencias y Adicciones</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/cursos">Cursos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/atPersonalizada">Atención Personalizada</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/retiros">Retiros</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/sobreMi">Sobre Mí</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/contacto">Contacto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/aPersonal">Area Personal</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <form id="frmCompra" asp-page="/Index" asp-page-handler="Comprar" method="post"></form>


    <!-- Modal -->
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title text-success" id="staticBackdropLabel">Carrito Inspira Libertad</h5>
                </div>
                <div class="modal-body">
                    Tu carrito está vacío.
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                    <button type="button" class="btn btn-success" onclick="comprar()">Comprar</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Button trigger modal -->
    <button type="button" id="btnCompra" class="btn btn-primary d-none" data-bs-toggle="modal" data-bs-target="#compraModal">
        Launch demo modal
    </button>

    <!-- Modal -->
    <div class="modal fade" id="compraModal" tabindex="-1" aria-labelledby="compraModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title text-success" id="compraModalLabel">Inspira Libertad</h5>
                </div>
                <div class="modal-body">
                    <span id="spnCompra"></span>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                </div>

            </div>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>